name: Deploy

on:
    workflow_run:
        workflows: ["Build", "Test"]
        types: [completed]
        branches: [main]

jobs:
    deploy-to-aws:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Download build artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                workflow: build.yml
                workflow_conclusion: success
                name: build-files
                path: build/

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --delete
              env:
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                SOURCE_DIR: "build"
            
            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
                  PATHS: "/*"
                  AWS_REGION: "us-east-1"
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}